"""Shared fail-closed filesystem primitives for checked contract generators.

Generators in this repository have two explicit modes: ``--check`` observes
the complete managed inventory without mutation, while ``--write`` replaces
reviewed generated bytes.  Shared roots use namespace patterns; dedicated
roots own every file below them.  An unexpected managed file is never deleted
implicitly and blocks writes until a reviewer removes it explicitly.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from fnmatch import fnmatchcase
import os
from pathlib import Path
import sys
import tempfile
from typing import Mapping, Sequence


@dataclass(frozen=True, slots=True)
class ManagedRoot:
    """Describe one exact or namespace-scoped generated-file root.

    ``patterns=None`` gives the generator ownership of every non-directory
    entry recursively below ``root``.  Otherwise only relative POSIX paths
    matching one of the supplied shell patterns belong to the generator.
    """

    root: Path
    patterns: tuple[str, ...] | None = None

    def claims(self, path: Path) -> bool:
        """Return whether ``path`` belongs to this managed inventory."""

        try:
            relative = path.relative_to(self.root)
        except ValueError:
            return False
        if relative == Path("."):
            return False
        if self.patterns is None:
            return True
        value = relative.as_posix()
        return any(fnmatchcase(value, pattern) for pattern in self.patterns)


@dataclass(frozen=True, slots=True)
class InventoryDrift:
    """Missing and unexpected paths for one generated inventory."""

    missing: tuple[Path, ...]
    extra: tuple[Path, ...]


def parse_check_mode(
    parser: argparse.ArgumentParser,
    argv: Sequence[str] | None,
) -> bool:
    """Parse one required, mutually exclusive generation mode.

    The return value is true for ``--check`` and false for ``--write``.
    ``argparse`` exits with status 2 for a missing mode or an attempt to supply
    both modes, before a generator can inspect or mutate managed outputs.
    """

    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument(
        "--check",
        action="store_true",
        help="verify exact managed bytes and inventory without writing",
    )
    modes.add_argument(
        "--write",
        action="store_true",
        help="atomically replace reviewed generated bytes",
    )
    return bool(parser.parse_args(argv).check)


def inventory_drift(
    expected_paths: Sequence[Path],
    managed_roots: Sequence[ManagedRoot],
) -> InventoryDrift:
    """Compare expected paths with every entry owned by ``managed_roots``."""

    expected = frozenset(expected_paths)
    for path in expected:
        owners = tuple(root for root in managed_roots if root.claims(path))
        if len(owners) != 1:
            raise ValueError(
                f"generated path must have exactly one managed root: {path}"
            )

    observed: set[Path] = set()
    for managed in managed_roots:
        if not managed.root.exists():
            continue
        for path in managed.root.rglob("*"):
            if path.is_dir() and not path.is_symlink():
                continue
            if managed.claims(path):
                observed.add(path)

    return InventoryDrift(
        tuple(sorted(expected - observed, key=_path_key)),
        tuple(sorted(observed - expected, key=_path_key)),
    )


def reconcile_generated_files(
    outputs: Mapping[Path, bytes],
    managed_roots: Sequence[ManagedRoot],
    *,
    check: bool,
    label: str,
) -> int:
    """Check or atomically update a complete generated-file inventory.

    Write mode refuses to touch expected outputs when an unexpected managed
    entry exists.  Extras require an explicit reviewed deletion, preventing a
    generator from silently erasing or legitimizing an orphan artifact.
    """

    expected = tuple(outputs)
    drift = inventory_drift(expected, managed_roots)
    stale = tuple(
        sorted(
            (
                path
                for path, content in outputs.items()
                if path not in drift.missing
                and (
                    path.is_symlink()
                    or not path.is_file()
                    or path.read_bytes() != content
                )
            ),
            key=_path_key,
        )
    )
    if check:
        if drift.missing or stale or drift.extra:
            _report_drift(label, drift, stale)
            return 1
        return 0
    if drift.extra:
        _report_drift(label, drift, stale)
        print(
            f"refusing to write {label}: remove unexpected managed files explicitly",
            file=sys.stderr,
        )
        return 1

    outdated = tuple(sorted((*drift.missing, *stale), key=_path_key))
    for path in outdated:
        atomic_write(path, outputs[path])
    return 0


def atomic_write(path: Path, content: bytes) -> None:
    """Durably replace one generated file and clean up on pre-replace failure."""

    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb", closefd=True) as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def _fsync_directory(path: Path) -> None:
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
    descriptor = os.open(path, flags)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _report_drift(
    label: str,
    drift: InventoryDrift,
    stale: tuple[Path, ...],
) -> None:
    for kind, paths in (
        ("missing", drift.missing),
        ("stale", stale),
        ("extra", drift.extra),
    ):
        if paths:
            print(
                f"{label} {kind}: " + ", ".join(map(str, paths)),
                file=sys.stderr,
            )


def _path_key(path: Path) -> str:
    return path.as_posix()
